name: bilitube
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-174.2.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.1.0
  prompts: ^2.0.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  process_run: ^0.13.3
  dartx: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
